### ISSUE TITLE
“环境”的切换（进入和退出）怎么操作呢？

### ISSUE THREAD

**Issue by lon91ong** [X-Wei/texmacs-demo#2]
[网站教程](http://x-wei.github.io/TeXmacs_intro.html#13-cha-ru-gai-shu)中第1.3节第一句“**从标题环境出来**”，这一步操作怎么做呢？
死活没找到，直接往下接着写还是在标题环境中啊！

**Comment by X-Wei** [comment]
按左右箭头 把光标移出相应环境的方框即可
